---
services:
  - redis-server

language: rust
cache: cargo
rust: stable

script:
  - cargo test -v

matrix:
  include:
    - rust: nightly
      env: CLIPPY=1
      script:
        - cargo rustc --lib --features "lint" -- -Zno-trans

notifications:
  email:
    on_success: change
    on_failure: always
