---
services:
  - redis
language: rust
cache: cargo

rust:
  - stable

matrix:
  include:
    - rust: stable
      env: FMT=1
      before_install:
        - cargo install just
      before_script:
        - rustup component add rustfmt
      script:
        - just format
    - rust: stable
      env: CLIPPY=1
      before_install:
        - cargo install just
      before_script:
        - rustup component add clippy
      script:
        - just lint
    - rust: stable
      env: TEST=1
      before_install:
        - cargo install just
      script:
        - just test

notifications:
  email:
    on_success: change
    on_failure: always
