[package]
name = "maman"
version = "0.11.0"
authors = ["Laurent Arnoud <laurent@spkdev.net>"]
description = "Rust Web Crawler"
repository = "https://github.com/spk/maman.git"
homepage = "https://github.com/spk/maman"
keywords = ["http", "web", "crawler", "spider"]
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "spk/maman" }

[dependencies]
reqwest = "0.4.0"
html5ever = "0.10"
html5ever-atoms = "0.1.3"
tendril = "0.2"
string_cache = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
url = "1.4.0"
url_serde = "0.1.0"
robotparser = "0.8.0"
sidekiq = "0.6.0"
encoding = "0.2"
log = "0.3"
env_logger = "0.3"
clippy = { version = "=0.0.122", optional = true }

[features]
unstable = []
lint = ["clippy"]
