[package]
name = "maman"
# When updating version, also modify html_root_url in the src/lib.rs file.
version = "0.13.1"
authors = ["Laurent Arnoud <laurent@spkdev.net>"]
description = "Rust Web Crawler"
repository = "https://github.com/spk/maman.git"
homepage = "https://github.com/spk/maman"
keywords = ["http", "web", "crawler", "spider"]
license = "MIT"
readme = "README.md"
exclude = ["Makefile", "rustfmt.toml"]

[badges]
travis-ci = { repository = "spk/maman" }

[dependencies]
reqwest = "0.9"
mime = "0.3"
html5ever = "0.22"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.4"
url_serde = "0.2"
robotparser = "0.10"
sidekiq = "0.8"
log = "0.4"
env_logger = "0.6"

[dev-dependencies]
mockito = "0.14"
